### ISSUE TITLE
Error on running server.go

### ISSUE THREAD

**Issue by alegroSandermann** [WTFender/csgobs#1]
Hi, I want to integrate my own functions with events.js. So I generated the static.go with go-bindata and also downloaded all dependencies for server.go, but if I run server.go I get the error
```
.\server.go:18:15: undefined: Asset
.\server.go:28:15: undefined: Asset
```

If I build the server.exe i get the message
`{"message":"Internal Server Error"}`
in the browser and the command line says `status":500,"error":"Asset index.html not found`

**Comment by WTFender** [comment]
Could you share your build commands?

I was able to reproduce the error by running this command:
```
PS D:\dev\csgobs> go build -o server.exe server.go

# command-line-arguments
.\server.go:18:15: undefined: Asset
.\server.go:28:15: undefined: Asset
```

However, the command should be like this to include `static.go`:
```
PS D:\dev\csgobs> go build -o server.exe . 
```

**Comment by alegroSandermann** [comment]
I build with `PS D:\csgobs> go build -o server.exe`
If I build with `PS D:\csgobs> go build -o server.exe .` I get the same error/result

**Comment by WTFender** [comment]
Are you building with your customized JS file? Could you try the default file to rule it out?

I can't say I fully understand how static.go encodes the assets or what errors it might be prone to.

What version are you on?
I built successfully on a couple machines with `go version go1.15 windows/amd64`

**Comment by alegroSandermann** [comment]
Ok, the problem must be somewhere from go-bindata. If I build server.exe with the original files from the repo everything works.
If I generate static.go with the original static files with go-bindata and then build the server.exe I get the error.
I am on: go-bindata 3.1.0 (Go runtime go1.15.6).

*edit*
ok I think I found the problem. The go-bindata command is wrong. I will test it.

**Comment by alegroSandermann** [comment]
So the problem was. If I generate static.go with
`PS D:\csgobs> go-bindata -o static.go static/`
the result in static.go is
`var _staticIndexHtml = []byte`
but it must be
`var _indexHtml = []byte`
so I have to generate static.go from the static folder with
`PS D:\csgobs\static> go-bindata -o static.go .`
and then copy the generated file one folder down to build the server.exe
